<a href="https://colab.research.google.com/github/Cesarpipe31/Alura_Python_DS_02_Numpy/blob/main/Python_Data_Science_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUCCIÓN A PYTHON
---

# 1.1 Introducción

> Python es un lenguaje de programación de alto nivel con soporte a múltiples paradigmas de programación. Es un proyecto *open source* y desde su surgimiento, en 1991, viene convirtiéndose en uno de los lenguajes de programación interpretados más populares.
>
> En los últimos años Python desarrolló una comunidad activa de procesamiento científico y análisis de datos y viene destacándose como uno de los lenguajes más relevantes cuando el asunto es ciencia de datos y machine learning, tanto en el entorno acadêmico como también en el entorno laboral.

# 1.2 Instalación y entorno de trabajo

### Instalación Local

### https://www.python.org/downloads/
### o
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versión

In [12]:
!python -V

Python 3.10.12


# 1.3 Trabajando con Numpy

In [13]:
import numpy as np

In [14]:
km = np.loadtxt('carros-km.txt', dtype = int)

In [15]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [16]:
años = np.loadtxt('carros-años.txt', dtype = int)

In [17]:
años

array([2003, 1991, 1990, 2020, 2006, 2012, 2020, 2009, 2010, 2011, 2002,
       2007, 2001, 2020, 2009, 2016, 2012, 2020, 2016, 2017, 2002, 2020,
       1994, 1991, 2020, 2020, 2016, 2020, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2020, 2020, 2009, 2020, 2013, 2003, 2020, 2002,
       2020, 2002, 2004, 2001, 2020, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2020, 2020, 2020, 2020, 2020, 2017, 2011, 2001, 1996,
       2020, 1994, 2020, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2020, 2020, 1999, 2007, 1993, 1995, 2020, 2020, 2016, 2011,
       2020, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2020, 2006, 2001, 2020, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2020, 2017, 2020, 2020, 2006, 2015, 2007,
       2005, 2017, 1998, 2020, 1999, 2020, 2009, 2003, 1994, 2020, 1994,
       2020, 2015, 1996, 1997, 1993, 2020, 1992, 1995, 2020, 1990, 2020,
       2020, 1991, 1990, 2012, 2007, 2013, 2000, 20

In [18]:
nombres = np.loadtxt('carros-nombres.txt', dtype=str, delimiter='\t')


In [19]:
nombres

array(['Jetta Variant', 'Passat', 'Crossfox', 'DS5', 'Aston Martin DB4',
       'Palio Weekend', 'A5', 'Serie 3 Cabrio', 'Dodge Jorney', 'Carens',
       'Ford Edge', 'Courier', 'S-18', 'J5', 'F-Type Coupe', 'RAM',
       'Serie 1', 'A3', 'XC90', 'RS 3 Sportback', 'Pajero Sport',
       'Serie 1 M', 'Lamborghini Obvious', 'Effa Hafei Picape Bau',
       'Lamborghini Murcielago', 'Up!', 'Fiesta Rocam Sedan',
       'Sandero Stepway', 'Cayman S', 'V40', 'Classe SLS AMG', 'Gol G4',
       'Linea', 'Ford F100', 'J2', 'Aston Martin DBS', 'Pajero TR4',
       'Polo Sedan', 'California', 'S60', 'Tucson', 'HB20', 'Optima',
       'Logan', 'Range Rover Vogue', 'Sonata', 'Ford New Fiesta Sedan',
       'Serie 5 Gran Turismo', 'CR-V', 'Ford EcoSport', 'Versa',
       'Classe E', 'Carnival', 'Aston Martin V8 Vantage Roadster',
       'Hoggar', 'A1', 'Aston Martin DB7 Vantage', 'CLA', 'Accord',
       'EXTRA 103EX', 'Sorento', 'Tiggo', 'New Fiesta Hatch',
       'Jeep Renegade', 'Lamborghini Ankoni

In [20]:
valor = np.loadtxt('carros-valor.txt', dtype = float)

In [21]:
valor

array([ 88078.64, 106161.94,  72832.16, 124549.07,  92612.1 ,  97497.73,
        56445.2 , 112310.44, 120716.27,  76566.49,  71647.59,  73919.53,
       112732.99,  53183.38, 127488.42,  59910.4 ,  61118.59,  88552.39,
        62696.69, 101726.3 , 106147.38,  94564.4 , 133529.84, 125684.65,
       121596.21,  71367.1 ,  95347.75, 105432.84,  57045.27, 120432.7 ,
        70707.2 ,  69105.18,  59358.69,  65955.4 ,  60017.03, 118909.52,
        51606.59, 123281.87,  69770.18, 102609.54,  67997.19, 135235.29,
        86641.34, 136818.39, 117626.73,  56208.7 ,  84222.65,  90781.65,
        64701.1 , 126350.49, 148152.89, 132298.83, 137627.63,  80422.71,
        56373.99,  70846.03, 128694.23, 133329.19, 131961.43, 112033.27,
        81399.35,  97163.1 ,  66007.16, 128776.22, 142623.02, 136930.13,
        66526.61, 114154.87, 142392.75, 146716.91, 122485.68,  97951.03,
        78283.49,  83434.04,  77836.23,  60813.92,  91353.86, 116281.21,
       145197.7 ,  50742.1 ,  73033.53,  54332.87, 

In [22]:
zero_km = np.loadtxt('carros-zero-km.txt', dtype = bool)

In [23]:
zero_km

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False,  True,  True, False,
        True, False, False, False, False, False, False, False, False,
        True,  True, False,  True, False, False,  True, False,  True,
       False, False, False,  True, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False, False,  True,  True, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
        True, False, False, False, False, False, False,  True, False,
        True, False,

### Obtener el promedio de kilometros recorridos por año

In [24]:
km_promedio = km / (2023 - años)

In [25]:
km_promedio

array([2.22050000e+03, 1.78500000e+02, 1.12493939e+03, 0.00000000e+00,
       1.51511765e+03, 9.75272727e+02, 0.00000000e+00, 5.54278571e+03,
       7.63053846e+03, 3.16483333e+03, 6.12333333e+02, 5.03250000e+02,
       4.08059091e+03, 0.00000000e+00, 2.96121429e+03, 1.65152857e+04,
       4.22263636e+03, 0.00000000e+00, 5.29800000e+03, 2.52883333e+03,
       4.81871429e+03, 0.00000000e+00, 3.38203448e+03, 3.21746875e+03,
       0.00000000e+00, 0.00000000e+00, 8.27857143e+02, 0.00000000e+00,
       2.80228571e+03, 2.94940625e+03, 1.16011538e+03, 1.90471429e+03,
       3.54400000e+03, 1.05650000e+03, 1.00760000e+04, 1.57053571e+03,
       0.00000000e+00, 0.00000000e+00, 3.94714286e+02, 0.00000000e+00,
       9.34150000e+03, 2.03810000e+03, 0.00000000e+00, 4.10961905e+03,
       0.00000000e+00, 4.64523810e+02, 3.68131579e+03, 1.08863636e+02,
       0.00000000e+00, 4.01745000e+03, 6.11100000e+03, 2.97035294e+03,
       2.94417391e+03, 5.52629412e+03, 2.71884615e+03, 2.79334483e+03,
      

In [26]:
type(km_promedio)

numpy.ndarray

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DEL LENGUAJE
---

# 2.1 Operaciones matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Suma ($+$)

In [27]:
2 + 2

4

### Resta ($-$)

In [28]:
2 - 2

0

### Multiplicación ($*$)

In [29]:
2 * 2

4

### División ($/$) y ($//$)
La operación división siempre devuelve un número con punto decimal

In [30]:
10 / 3

3.3333333333333335

In [31]:
10 // 3

3

### Exponenciación ($**$)

In [32]:
2 ** 3

8

### Resto de la división ($\%$)

In [33]:
10 % 3

1

In [34]:
10 % 2

0

### Expresiones matemáticas

In [35]:
5 * 2 + 3 * 2

16

In [36]:
(5 * 2) + (3 * 2)

16

In [37]:
5 * (2 + 3) * 2

50

### La variable _

En el modo interactivo, el último resultado impreso en pantalla es atribuído a la variable _

In [38]:
5 * 2

10

In [39]:
_

10

In [40]:
_ + 3 * 2

16

# 2.2 Variables

### Nombres de variables

- Nombres de variables pueden comenzar con letras (a - z, A - Z) o con el símbolo *underscore* (_):

    > Altura
    >
    > _peso
    
- El resto del nombre puede contener letras, números o el símbolo "_":

    > nombre_de_variable
    >
    > _valor
    >
    > dia_28_11_
    

- Los nombres son *case sensitive*:

    > Nombre_De_Variable $\ne$ nombre_de_variable $\ne$ NOMBRE_DE_VARIABLE
    
### <font color=red>Observaciones:
- Existen algumas palabras reservadas del lenguaje que no pueden ser utilizadas como nombres de variables:

| |Lista de palabras <br>reservadas en Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           |
| assert        | finally      | or            |
| break         | for          | pass          |
| class         | from         | nonlocal      |
| continue      | global       | raise         |
| def           | if           | return        |
| del           | import       | try           |
| elif          | in           | while         |
| else          | is           | with          |
| except        | lambda       | yield         |
| False         | True         | None          |

### Declaración de variables

### Operadores de asignación: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [41]:
año_actual = 2023
año_fabricacion = 2003
km_total = 44410.0

In [42]:
año_actual

2023

In [43]:
año_fabricacion

2003

In [44]:
km_total

44410.0

# $$km_{promedio} = \frac {km_{total}}{(Año_{actual} - Año_{fabricación})}$$

### Operaciones con variables

In [45]:
km_promedio = km_total / (año_actual - año_fabricacion)

In [46]:
año_actual = 2023
año_fabricacion = 2003
km_total = 44410.0
km_promedio = km_total / (año_actual - año_fabricacion)
km_promedio

km_total = km_total + km_promedio
km_total

46630.5

In [47]:
año_actual = 2023
año_fabricacion = 2003
km_total = 44410.0
km_promedio = km_total / (año_actual - año_fabricacion)
km_promedio

km_total +=  km_promedio
km_total

46630.5

### Conclusión:
```
"valor = valor + 1" es equivalente a "valor += 1"
```

### Declaración múltiple

In [48]:
año_actual,  año_fabricacion, km_total = 2023, 2003, 44410.0

In [49]:
año_actual

2023

In [50]:
año_fabricacion

2003

In [51]:
km_total

44410.0

# 2.3 Tipos de datos

Los tipos de datos especifican como números y caracteres estarán guardados y manipulados dentro de un programa. Los tipos de datos básicos en Python son:

1. **Números**
    1. ***int*** - Enteros
    - ***float*** - Decimales
- **Booleanos** - Contiene valores True o False. Esencial cuando comenzamos a trabajar con declaraciones condicionales
- ***Strings*** - Secuencia de uno o más caracteres que puede incluir letras, números y otros tipos de caracteres. Representa un texto.
- **None** - Representa la ausencia de valor

### Números

In [52]:
año_actual = 2023

In [53]:
type(año_actual)

int

In [54]:
km_total = 44410.0

In [55]:
type(km_total)

float

### Booleanos

In [56]:
zero_km = True

In [57]:
type(zero_km)

bool

In [58]:
zero_km = False

In [59]:
type(zero_km)

bool

### Strings

In [60]:
nombre = 'Jetta Variant'
nombre

'Jetta Variant'

In [61]:
nombre = "Jetta Variant"
nombre

'Jetta Variant'

In [62]:
nombre = 'Jetta "Variant"'
nombre

'Jetta "Variant"'

In [63]:
nombre = "Jetta 'Variant'"
nombre

"Jetta 'Variant'"

In [64]:
carro = '''
  Nombre
  Edad
  Nota
  '''

carro


'\n  Nombre\n  Edad\n  Nota\n  '

In [65]:
carro
type(carro)

str

### None

In [66]:
kilometraje = None
kilometraje

In [67]:
type(kilometraje)

NoneType

# 2.4 Conversión de tipos

In [68]:
a = 10
b = 20
c = 'Python es '
d = 'genial'

In [69]:
type(a)

int

In [70]:
type(b)

int

In [71]:
type(c)

str

In [72]:
type(d)

str

In [73]:
a + b

30

In [74]:
c + d

'Python es genial'

In [75]:
# c + a

### Conversiones de tipo

Funciones int(), float(), str()

In [76]:
str(a)

'10'

In [77]:
type(str(a))

str

In [78]:
c + str(a)

'Python es 10'

In [79]:
float(a)

10.0

In [80]:
var = 3.141592

In [81]:
int(var)

3

In [82]:
var = 3.99

In [83]:
int(var)

3

# 2.5 Indentación, comentarios y formatación de *strings*

### Indentación

En el lenguaje Python los programas son estructurados por medio de indentación. En cualquier lenguaje de programación la práctica de colocar indentación es bastante útil, facilitando la lectura y también el mantenimiento del código. En Python la indentación no es solamente una cuestión de organización y estilo, sino que es un requisito del lenguaje.

In [84]:
año_actual = 2020
año_fabricacion = 2020

if (año_actual == año_fabricacion):
    print('Verdadero')
else:
    print('Falso')

Verdadero


### Comentarios

Comentarios son extremamente importantes en un programa. Consiste en un texto que describe lo que el programa o una parte específica del programa está haciendo. Los comentarios son ignorados por el interpretador Python.

Podemos tener comentarios de una única linea o de múltiples líneas.

In [85]:
# Esto es un comentario
año_actual = 2020
año_actual

2020

In [86]:
# Esto
# es un
# comentario
año_actual = 2020
año_actual

2020

In [87]:
'''Esto es un
comentario'''
año_actual = 2020
año_actual

2020

In [88]:
# Definiendo variables
año_actual = 2020
año_fabricacion = 2020

'''
Estructura condicional que vamos
a aprender la próxima clase
'''
if (año_actual == año_fabricacion):   # Probando si la condición es verdadera
    print('Verdadero')
else:                               # Probando si la condición es falsa
    print('Falso')

Verdadero


### Formatación de *strings*

## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [89]:
print('Hola, {}'.format('César'))

Hola, César


In [90]:
print ('Hola {}, esta es su visita número {}'.format('César', 33))

Hola César, esta es su visita número 33


## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

# <font color=green> 3. TRABAJANDO CON LISTAS
---

# 3.1 Creando listas

Listas son secuencias **mutables** que son utilizadas para guardar colecciones de objetos, generalmente homogéneos. Pueden ser construídas de varias formas:
```
- Utilizando un par de corchetes: [ ], [ 1 ]
- Utilizando un par de corchetes con objetos separados por comas: [ 1, 2, 3 ]
```

In [91]:
Accesorios = ['Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de lluvia']
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

### Lista con tipos de datos variados

In [92]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Cerraduras eléctricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimedia', 'Frenos ABS'], 106161.94]

In [93]:
type(Accesorios)

list

In [94]:
Carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Cerraduras eléctricas', 'Piloto automático'],
 88078.64]

In [95]:
Carro_2

['Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimedia', 'Frenos ABS'],
 106161.94]

In [96]:
Carros = [Carro_1, Carro_2]
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Cerraduras eléctricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimedia', 'Frenos ABS'],
  106161.94]]

# 3.2 Operaciones con listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

## *x in A*

Devuelve **True** si un elemento de la lista *A es igual a x*.

In [97]:
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [98]:
'Cerraduras eléctricas' in Accesorios

True

In [99]:
'Cerraduras eléctricas' not in Accesorios

False

In [100]:
'4x4' in Accesorios

False

## *A + B*

Concatena las listas *A y B*.

In [101]:
A = ['Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero']
B = ['Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de lluvia']

In [102]:
A + B

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

## *len(A)*

Tamaño de la lista A.

In [103]:
len(Accesorios)

6

# 3.3 Selecciones en listas

## *A[ n ]*

Devuelve el n-ésimo objeto de la lista *A*.

<font color=red>**Observación:**</font> Listas tienen indexación con inicio en cero.

In [104]:
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [105]:
Accesorios[0]

'Cerraduras eléctricas'

In [106]:
Accesorios[1]

'Piloto automático'

In [107]:
Accesorios[-1]

'Sensor de lluvia'

In [108]:
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Cerraduras eléctricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimedia', 'Frenos ABS'],
  106161.94]]

In [109]:
Carros[0][0]

'Jetta Variant'

In [110]:
Carros[1][0]

'Passat'

In [111]:
Carros[0][-2]

['Cerraduras eléctricas', 'Piloto automático']

In [112]:
Carros[0][-2][-1]

'Piloto automático'

## *A[ i : j ]*

Recorta la lista A desde el índice i hasta j. En este recorte el elemento con índice i **es incluído** y el elemento con índice j **no es incluído** en el resultado.

In [113]:
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [114]:
Accesorios[2:5]

['Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento']

In [115]:
Accesorios[2:]

['Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [116]:
Accesorios[:2]

['Cerraduras eléctricas', 'Piloto automático']

# 3.4 Métodos en listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena la lista *A*.

In [117]:
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [118]:
Accesorios.sort()
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

## *A.append(x)*

Añade el elemento *x al final de la lista A*

In [119]:
Accesorios.append("4 x 4")
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 '4 x 4']

## *A.pop(i)*

Elimina y devuelve el elemento de índice i de la lista *A*.

<font color=red>**Observación:**</font> Por *defecto* el método *pop()* elimina y devuelve el último elemento de una lista.

In [120]:
Accesorios.pop()

'4 x 4'

In [121]:
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [122]:
Accesorios.pop()

'Sensor de lluvia'

In [123]:
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento']

In [124]:
Accesorios.pop(3)

'Piloto automático'

In [125]:
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento']

## *A.copy()*

Crea una copia de la lista *A*.

<font color=red>**Observación:**</font> El mismo resultado puede ser obtenido con el seguinte código:
```
A[:]
```

In [126]:
Accesorios_2 = Accesorios
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento']

In [127]:
Accesorios_2.append('4 x 4')
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 '4 x 4']

In [128]:
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 '4 x 4']

In [129]:
Accesorios
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 '4 x 4']

In [130]:
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 '4 x 4']

In [131]:
Accesorios.pop()

'4 x 4'

In [132]:
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento']

In [133]:
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento']

In [134]:
Accesorios_2 = Accesorios.copy()
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento']

In [135]:
Accesorios_2.append('4 x 4')
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 '4 x 4']

In [136]:
Accesorios_2 = Accesorios[:]
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento']

# <font color=green> 4. ESTRUCTURAS DE REPETICIÓN Y CONDICIONALES
---

# 4.1 Instrucción *for*

#### Formato estándar

```
for <variable> in <coleccion>:
    <instrucciones>
```

### Loops con listas

In [137]:
# Ejercicio Alura
Accesorios1 = [
    'Llantas de aleación',
    'Cerraduras eléctricas',
    'Piloto automático',
    'Bancos de cuero',
    'Aire acondicionado'
]

In [138]:
# Ejercicio Alura RESPUESTA
Accesorios1.append('Airbag')
Accesorios1.sort()
Accesorios1.pop()
Accesorios1.append('Ventanas eléctricas')
Accesorios1

['Airbag',
 'Aire acondicionado',
 'Bancos de cuero',
 'Cerraduras eléctricas',
 'Llantas de aleación',
 'Ventanas eléctricas']

In [139]:
Accesorios = ['Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de lluvia']

In [140]:
for elemento in Accesorios:
  print(elemento)

Cerraduras eléctricas
Piloto automático
Asientos de cuero
Aire acondicionado
Sensor de estacionamiento
Sensor de lluvia


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [141]:
range(10)

range(0, 10)

In [142]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [143]:
for i in range(10):
  print(i ** 2)

0
1
4
9
16
25
36
49
64
81


In [144]:
cuadrado = []


for i in range(10):
  cuadrado.append(i ** 2)


cuadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [145]:
# SUPERIMPORTANTE.  Se hace en una sola línea

cuadrado = [ i ** 2 for i in range (10)]

cuadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

# 4.2 Loops anidados

In [146]:
datos = [
    ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de crepúsculo', 'Sensor de lluvia'],
    ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento'],
    ['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática', 'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']
]
datos

[['Llantas de aleación',
  'Cerraduras eléctricas',
  'Piloto automático',
  'Asientos de cuero',
  'Aire acondicionado',
  'Sensor de estacionamiento',
  'Sensor de crepúsculo',
  'Sensor de lluvia'],
 ['Central multimedia',
  'Techo panorámico',
  'Frenos ABS',
  '4 X 4',
  'Panel digital',
  'Piloto automático',
  'Asientos de cuero',
  'Cámara de estacionamiento'],
 ['Piloto automático',
  'Control de estabilidad',
  'Sensor crepuscular',
  'Frenos ABS',
  'Transmisión automática',
  'Asientos de cuero',
  'Central multimedia',
  'Ventanas eléctricas']]

In [147]:
for i in datos:
  for j in i:
    print(j)

Llantas de aleación
Cerraduras eléctricas
Piloto automático
Asientos de cuero
Aire acondicionado
Sensor de estacionamiento
Sensor de crepúsculo
Sensor de lluvia
Central multimedia
Techo panorámico
Frenos ABS
4 X 4
Panel digital
Piloto automático
Asientos de cuero
Cámara de estacionamiento
Piloto automático
Control de estabilidad
Sensor crepuscular
Frenos ABS
Transmisión automática
Asientos de cuero
Central multimedia
Ventanas eléctricas


In [148]:
Accesorios = []

for lista in datos:
  for item in lista:
    Accesorios.append(item)

Accesorios

['Llantas de aleación',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de crepúsculo',
 'Sensor de lluvia',
 'Central multimedia',
 'Techo panorámico',
 'Frenos ABS',
 '4 X 4',
 'Panel digital',
 'Piloto automático',
 'Asientos de cuero',
 'Cámara de estacionamiento',
 'Piloto automático',
 'Control de estabilidad',
 'Sensor crepuscular',
 'Frenos ABS',
 'Transmisión automática',
 'Asientos de cuero',
 'Central multimedia',
 'Ventanas eléctricas']

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [149]:
set (Accesorios)

{'4 X 4',
 'Aire acondicionado',
 'Asientos de cuero',
 'Central multimedia',
 'Cerraduras eléctricas',
 'Control de estabilidad',
 'Cámara de estacionamiento',
 'Frenos ABS',
 'Llantas de aleación',
 'Panel digital',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de crepúsculo',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 'Techo panorámico',
 'Transmisión automática',
 'Ventanas eléctricas'}

In [150]:
list(set(Accesorios))

['Central multimedia',
 'Piloto automático',
 'Sensor de lluvia',
 'Llantas de aleación',
 'Aire acondicionado',
 'Sensor de crepúsculo',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Techo panorámico',
 'Ventanas eléctricas',
 'Control de estabilidad',
 'Sensor de estacionamiento',
 'Panel digital',
 '4 X 4',
 'Frenos ABS',
 'Sensor crepuscular',
 'Transmisión automática',
 'Cámara de estacionamiento']

### List comprehensions

In [151]:
Accesorios = list(set([item for lista in datos for item in lista]))

Accesorios

['Central multimedia',
 'Piloto automático',
 'Sensor de lluvia',
 'Llantas de aleación',
 'Aire acondicionado',
 'Sensor de crepúsculo',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Techo panorámico',
 'Ventanas eléctricas',
 'Control de estabilidad',
 'Sensor de estacionamiento',
 'Panel digital',
 '4 X 4',
 'Frenos ABS',
 'Sensor crepuscular',
 'Transmisión automática',
 'Cámara de estacionamiento']

# 4.3 Instrucción *if*

#### Formato estándar

```
if <condicion>:
     <instrucciones en caso la condición sea verdadera>
```

### Operadores de comparación: $==$, $!=$, $>$, $<$, $>=$, $<=$
### y
### Operadores lógicos: $and$, $or$, $not$

In [152]:
# 1º objeto de la lista - Nombre del vehículo
# 2º objeto de la lista - Año de fabricación
# 3º objeto de la lista - Vehículo es cero km?

datos = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
datos

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [153]:
cero_km_T = []


for lista in datos:
  if (lista[2] == True):
    cero_km_T.append(lista)


cero_km_T

[['DS5', 2019, True], ['A5', 2019, True]]

In [154]:
cero_km_F = []


for lista in datos:
  if (lista[2] == False):
    cero_km_F.append(lista)


cero_km_F

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

### List comprehensions

In [155]:
cero_km_T = [lista for lista in datos if(lista[2] == True)]

cero_km_T

[['DS5', 2019, True], ['A5', 2019, True]]

# 4.4 Instrucciones *if-else* y *if-elif-else*

#### Formato estándar

```
if <condicion>:
    <instrucciones en caso la condición sea verdadera>
else:
    <instrucciones en caso la condición no sea verdadera>
```

#### Formato estándar

```
if <condicion 1>:
    <instrucciones en caso la condición 1 sea verdadera>
elif <condicion 2>:
    <instrucciones en caso la condición 2 sea verdadera>
elif <condicion 3>:
    <instrucciones en caso la condición 3 sea verdadera>
                        .
                        .
                        .
else:
    <instrucciones en caso las condiciones anteriores no sean verdaderas>
```

In [156]:
print('AND')
print(f'(True and True) el resultado es: {True and True}')
print(f'(True and False) el resultado es: {True and False}')
print(f'(False and True) el resultado es: {False and True}')
print(f'(False and False) el resultado es: {False and False}')

AND
(True and True) el resultado es: True
(True and False) el resultado es: False
(False and True) el resultado es: False
(False and False) el resultado es: False


In [157]:
print('OR')
print(f'(True or True) el resultado es: {True or True}')
print(f'(True or False) el resultado es: {True or False}')
print(f'(False or True) el resultado es: {False or True}')
print(f'(False or False) el resultado es: {False or False}')

OR
(True or True) el resultado es: True
(True or False) el resultado es: True
(False or True) el resultado es: True
(False or False) el resultado es: False


In [158]:
A, B, C = [], [], []

for lista in datos:
  if(lista[1] <= 2000):
    A.append(lista)
  elif(lista[1] > 2000 and lista[1] <= 2010):
    B.append(lista)
  else:
    C.append(lista)

In [159]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [160]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [161]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# <font color=green> 5. NUMPY BÁSICO
---

Numpy es la abreviación de Numerical Python y es uno de los paquetes más importantes para procesamiento numérico en Python. Numpy ofrece la base para la mayoría de los paquetes de aplicaciones científicas que usen datos numéricos en Python (estructuras de datos y algoritmos). Pueden destacarse los siguientes recursos que el paquete Numpy contiene:

- Un poderoso objeto array multidimensional;
- Funciones matemáticas sofisticadas para operaciones con arrays sin la necesidad de utilización de bucles *for*;
- Recursos de algebra linear y generación de números aleatórios

Además de sus obvios usos científicos, el paquete NumPy también es muy utilizado en análisis de datos como un eficiente contenedor multidimensional de datos genéricos para transporte entre diversos algoritmos y bibliotecas en Python.

**Versión:** 1.18.4

**Instalación:** https://scipy.org/install.html

**Documentación:** https://numpy.org/doc/1.18/

### Paquetes

Existen diversos paquetes Python disponibles para download en internet. Cada paquete tiene como objetivo la solución de determinado tipo de problema y para esto son desarrollados nuevos tipos, funciones y métodos.

Algunos paquetes son bastante utilizados en un contexto de ciencia de datos, como por ejemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Algunos paquetes no son distribuidos en la instalación estándar de Python. En este caso debemos instalar los paquetes que necesitamos en nuestro sistema para poder utilizar sus funcionalidades.

### Importando todo el paquete

In [168]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [169]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo el paquete y asignándole un nuevo nombre

In [170]:
import numpy as np

In [171]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte del paquete

In [174]:
from numpy import arange

In [176]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Creando arrays Numpy

In [177]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [179]:
km = np.array([1000, 2300, 4987, 1500])

In [180]:
km

array([1000, 2300, 4987, 1500])

In [181]:
type(km)

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [182]:
km.dtype

dtype('int64')

### A partir de datos externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [183]:
km = np.loadtxt(fname= 'carros-km.txt', dtype = int)

In [184]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [185]:
km.dtype

dtype('int64')

### Arrays con dos dimensiones

In [162]:
datos = [
    ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de crepúsculo', 'Sensor de lluvia'],
    ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento'],
    ['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática', 'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']
]
datos

[['Llantas de aleación',
  'Cerraduras eléctricas',
  'Piloto automático',
  'Asientos de cuero',
  'Aire acondicionado',
  'Sensor de estacionamiento',
  'Sensor de crepúsculo',
  'Sensor de lluvia'],
 ['Central multimedia',
  'Techo panorámico',
  'Frenos ABS',
  '4 X 4',
  'Panel digital',
  'Piloto automático',
  'Asientos de cuero',
  'Cámara de estacionamiento'],
 ['Piloto automático',
  'Control de estabilidad',
  'Sensor crepuscular',
  'Frenos ABS',
  'Transmisión automática',
  'Asientos de cuero',
  'Central multimedia',
  'Ventanas eléctricas']]

In [186]:
Accesorios = np.array(datos)

In [187]:
Accesorios

array([['Llantas de aleación', 'Cerraduras eléctricas',
        'Piloto automático', 'Asientos de cuero', 'Aire acondicionado',
        'Sensor de estacionamiento', 'Sensor de crepúsculo',
        'Sensor de lluvia'],
       ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4',
        'Panel digital', 'Piloto automático', 'Asientos de cuero',
        'Cámara de estacionamiento'],
       ['Piloto automático', 'Control de estabilidad',
        'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática',
        'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']],
      dtype='<U25')

In [188]:
km.shape

(258,)

In [189]:
Accesorios.shape

(3, 8)

### Comparando desempeño con listas

In [190]:
np_array = np.arange(1000000)

In [191]:
py_list = list(range(1000000))

In [192]:
%time for _ in range(100): np_array *= 2

CPU times: user 61 ms, sys: 630 µs, total: 61.6 ms
Wall time: 60.7 ms


In [193]:
%time for _ in range(100): py_list = [x*2 for x in py_list]

CPU times: user 9.7 s, sys: 2.6 s, total: 12.3 s
Wall time: 12.9 s


# 5.2 Operaciones aritméticas con arrays Numpy

### Operaciones entre arrays y constantes

In [194]:
km = [44410., 5712., 37123., 0., 25757.]
años = [2003, 1991, 1990, 2019, 2006]

In [ ]:
edad = 2023 - años

In [198]:
km = np.array([44410., 5712., 37123., 0., 25757.])
años = np.array([2003, 1991, 1990, 2019, 2006])

In [199]:
edad = 2023 - años

In [200]:
edad

array([20, 32, 33,  4, 17])

### Operaciones entre arrays

In [201]:
km_media = km / edad

In [202]:
km_media

array([2220.5       ,  178.5       , 1124.93939394,    0.        ,
       1515.11764706])

### Operaciones con arrays de dos dimensiones

In [204]:
datos = np.array([km, años])

In [205]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [206]:
datos.shape

(2, 5)

In [207]:
type(datos)

numpy.ndarray

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [208]:
datos[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [209]:
datos[1]

array([2003., 1991., 1990., 2019., 2006.])

In [211]:
km_media = km[0] / (2023 - datos[1])
km_media

array([ 2220.5       ,  1387.8125    ,  1345.75757576, 11102.5       ,
        2612.35294118])

# 5.3 Selecciones con arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexación

<font color=red>**Observación:**</font> La indexación tiene inicio en cero.

## <font color=green>**Consejo:**</font>
### *ndarray[ linea ][ columna ]* o *ndarray[ linea, columna ]*

 ### Particiones

La sintaxis para realizar particiones en un array Numpy es $i : j : k$ donde $i$ es el índice inicial, $j$ es el índice final, y $k$ es el indicador de intervalo ($k\neq0$)

<font color=red>**Observación:**</font> En las particiones (*slices*) el objeto con índice i es **incluído** y el objeto con índice j **no es incluído** en el resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

### Indexación con array booleano

<font color=red>**Observación:**</font> Selecciona un grupo de líneas y columnas siguiendo las etiquetas o un array booleano.

# 5.4 Atributos y métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

## *ndarray.shape*

Devuelve una tupla con las dimensiones del array.

## *ndarray.ndim*

Devuelve el número de dimensiones del array.

## *ndarray.size*

Devuelve el número de elementos del array.

## *ndarray.dtype*

Devuelve el tipo de datos de los elementos del array.

## *ndarray.T*

Devuelve el array transpuesto, es decir, convierte líneas en columnas y viceversa.

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

## *ndarray.tolist()*

Devuelve el array como una lista Python.

## *ndarray.reshape(shape[, order])*

Devuelve un array que contiene los mismos datos con una nueva forma.

In [165]:
km = [44410, 5712, 37123, 0, 25757]
años = [2003, 1991, 1990, 2019, 2006]

## *ndarray.resize(new_shape[, refcheck])*

Cambia la forma y el tamaño del array.

# 5.5 Estadísticas con arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

y

https://numpy.org/doc/1.16/reference/routines.statistics.html

y

https://numpy.org/doc/1.16/reference/routines.math.html

In [166]:
años = np.loadtxt(fname = "carros-años.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

## *np.mean()*

Devuelve el promedio de los elementos del array a lo largo del eje especificado.

## *np.std()*

Devuelve la desviación estándar de los elementos del array a lo largo del eje especificado.

## *ndarray.sum()*

Devuelve la suma de los elementos del array a lo largo del eje especificado.

## *np.sum()*

Devuelve la suma de los elementos del array a lo largo del eje especificado.